SET NAMES utf8mb4;
USE smart_contract_db;

ALTER TABLE risk_item
  MODIFY COLUMN risk_type VARCHAR(50) NOT NULL
  COMMENT 'risk category: LEGAL_COMPLIANCE/PERFORMANCE_DELIVERY/PAYMENT_SETTLEMENT/IP_CONFIDENTIALITY/LIABILITY_APPROVAL';

UPDATE risk_item
SET risk_type = CASE
  WHEN risk_type IN ('LEGAL_COMPLIANCE', 'PERFORMANCE_DELIVERY', 'PAYMENT_SETTLEMENT', 'IP_CONFIDENTIALITY', 'LIABILITY_APPROVAL')
    THEN risk_type
  WHEN risk_type IN ('BUSINESS', 'PERFORMANCE', 'DELIVERY') THEN 'PERFORMANCE_DELIVERY'
  WHEN risk_type IN ('PAYMENT', 'FINANCE', 'SETTLEMENT') THEN 'PAYMENT_SETTLEMENT'
  WHEN risk_type IN ('IP', 'CONFIDENTIALITY', 'SECRET') THEN 'IP_CONFIDENTIALITY'
  WHEN risk_type IN ('LIABILITY', 'APPROVAL') THEN 'LIABILITY_APPROVAL'
  ELSE 'LEGAL_COMPLIANCE'
END;
