CREATE TABLE IF NOT EXISTS `contract_attachment_ocr` (
  `ocr_id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'OCR结果ID',
  `attachment_id` bigint unsigned NOT NULL COMMENT '附件ID',
  `ocr_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'PENDING' COMMENT 'OCR状态：PENDING/PROCESSING/SUCCESS/FAILED',
  `preview_html` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '坐标原样还原HTML，用于页面预览',
  `plain_text` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'OCR纯文本，用于复制、检索和AI分析',
  `ocr_blocks_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'OCR结构化块JSON，包含page、bbox、text等信息',
  `ocr_raw_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'OCR原始返回JSON',
  `qwen_layout_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '千问版面分析JSON',
  `parse_source` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '解析来源：PDFBOX/OCR/qwen_layout等',
  `approximate` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否近似识别',
  `parse_warnings` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '解析告警',
  `page_count` int DEFAULT NULL COMMENT '页数',
  `ocr_model` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'OCR模型',
  `qwen_model` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '千问模型',
  `ocr_duration_ms` bigint DEFAULT NULL COMMENT 'OCR耗时毫秒',
  `qwen_duration_ms` bigint DEFAULT NULL COMMENT '千问耗时毫秒',
  `ocr_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'OCR错误信息',
  `created_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `version` int NOT NULL DEFAULT '1',
  PRIMARY KEY (`ocr_id`),
  UNIQUE KEY `uk_attachment_ocr_attachment` (`attachment_id`),
  KEY `idx_attachment_ocr_status` (`ocr_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='附件OCR识别结果表';
