CREATE TABLE `fulfillment_deliverable` (
  `deliverable_id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'deliverable id',
  `plan_id` bigint unsigned DEFAULT NULL COMMENT 'fulfillment plan id',
  `contract_id` bigint unsigned NOT NULL COMMENT 'contract id',
  `deliverable_type` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'deliverable type',
  `deliverable_name` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'deliverable name',
  `stage_name` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'stage name',
  `confirm_method` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'CHECKLIST' COMMENT 'confirm method',
  `status` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'PENDING_SUBMIT' COMMENT 'deliverable workflow status',
  `confirmed` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'confirmed flag',
  `confirm_status` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'CONFIRMED' COMMENT 'ai/manual confirm status',
  `source_clause` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'source clause',
  `ai_confidence` decimal(5,4) DEFAULT NULL COMMENT 'ai confidence',
  `ai_extracted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'ai extracted flag',
  `file_id` bigint unsigned DEFAULT NULL COMMENT 'uploaded file id',
  `confirmer` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'confirmer',
  `confirmed_at` datetime DEFAULT NULL COMMENT 'confirmed time',
  `acceptance_passed` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'acceptance passed flag',
  `accepted_by` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'acceptance operator',
  `accepted_at` datetime DEFAULT NULL COMMENT 'acceptance time',
  `submitted_by` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'submitter',
  `submitted_at` datetime DEFAULT NULL COMMENT 'submitted time',
  `reviewer_name` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'reviewer',
  `reviewed_at` datetime DEFAULT NULL COMMENT 'reviewed time',
  `review_comment` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'review comment',
  `submission_version` int unsigned NOT NULL DEFAULT '0' COMMENT 'submission version',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'remark',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'delete flag',
  PRIMARY KEY (`deliverable_id`),
  KEY `idx_deliverable_plan` (`plan_id`,`confirmed`),
  KEY `idx_deliverable_contract` (`contract_id`,`deliverable_type`,`confirmed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='fulfillment deliverable';
