CREATE TABLE `fulfillment_plan` (
  `plan_id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'plan id',
  `contract_id` bigint unsigned NOT NULL COMMENT 'contract id',
  `node_name` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'node name',
  `plan_type` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'OTHER' COMMENT 'plan type',
  `due_date` date DEFAULT NULL COMMENT 'due date',
  `status` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'TODO' COMMENT 'status',
  `progress` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'progress',
  `owner_name` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'owner name',
  `source_type` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'MANUAL' COMMENT 'source type',
  `extracted_rule` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'extract rule',
  `source_clause` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'source clause',
  `ai_confidence` decimal(5,4) DEFAULT NULL COMMENT 'ai confidence',
  `ai_extracted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'ai extracted flag',
  `confirm_status` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'CONFIRMED' COMMENT 'confirm status',
  `overdue_days` int unsigned NOT NULL DEFAULT '0' COMMENT 'current overdue days',
  `last_overdue_at` datetime DEFAULT NULL COMMENT 'last overdue marked time',
  `delay_status` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'NONE' COMMENT 'delay approval status',
  `delay_requested_due_date` date DEFAULT NULL COMMENT 'requested due date',
  `delay_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'delay reason',
  `delay_requested_by` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'delay requester',
  `delay_requested_at` datetime DEFAULT NULL COMMENT 'delay requested time',
  `delay_confirmed_by` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'delay confirmer',
  `delay_confirmed_at` datetime DEFAULT NULL COMMENT 'delay confirmed time',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'remark',
  `handled_at` datetime DEFAULT NULL COMMENT 'handled time',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'delete flag',
  PRIMARY KEY (`plan_id`),
  KEY `idx_fulfillment_contract` (`contract_id`,`due_date`,`status`),
  KEY `idx_fulfillment_due` (`due_date`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='fulfillment plan';

CREATE TABLE `fulfillment_overdue_history` (
  `history_id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'history id',
  `plan_id` bigint unsigned NOT NULL COMMENT 'plan id',
  `contract_id` bigint unsigned NOT NULL COMMENT 'contract id',
  `node_name` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'node name snapshot',
  `due_date` date DEFAULT NULL COMMENT 'overdue due date',
  `overdue_days` int unsigned NOT NULL DEFAULT '0' COMMENT 'overdue days',
  `status` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'OPEN' COMMENT 'history status',
  `started_at` datetime NOT NULL COMMENT 'overdue started time',
  `resolved_at` datetime DEFAULT NULL COMMENT 'resolved time',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'delete flag',
  PRIMARY KEY (`history_id`),
  KEY `idx_overdue_history_plan` (`plan_id`,`status`),
  KEY `idx_overdue_history_contract` (`contract_id`,`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='fulfillment overdue history';
